import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

import "../public/globals.css";

// Instantiate the font at the module scope
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stude | ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
